<map id="pytest_userver.plugins.log_capture.BaseError" name="pytest_userver.plugins.log_capture.BaseError">
<area shape="rect" id="Node000001" title=" " alt="" coords="140,37,333,77"/>
<area shape="rect" id="Node000003" href="$d9/df2/classpytest__userver_1_1plugins_1_1log__capture_1_1ClientConnectTimeoutError.html" title=" " alt="" coords="381,5,640,45"/>
<area shape="poly" id="edge2_Node000001_Node000003" title=" " alt="" coords="347,42,381,38,382,43,348,47"/>
<area shape="rect" id="Node000004" href="$d3/dab/classpytest__userver_1_1plugins_1_1log__capture_1_1IncorrectUsageError.html" title=" " alt="" coords="405,69,616,109"/>
<area shape="poly" id="edge3_Node000001_Node000004" title=" " alt="" coords="348,68,406,74,405,80,347,73"/>
<area shape="rect" id="Node000002" title=" " alt="" coords="5,45,92,70"/>
<area shape="poly" id="edge1_Node000001_Node000002" title=" " alt="" coords="106,55,140,55,140,60,106,60"/>
</map>
