<map id="pytest_userver.plugins.dynamic_config.UnknownConfigError" name="pytest_userver.plugins.dynamic_config.UnknownConfigError">
<area shape="rect" id="Node000001" title="Invalid dynamic config name in @pytest.mark.config." alt="" coords="5,167,235,207"/>
<area shape="rect" id="Node000002" href="$de/df6/classpytest__userver_1_1plugins_1_1dynamic__config_1_1BaseError.html" title="Base class for exceptions from this module." alt="" coords="5,79,235,119"/>
<area shape="poly" id="edge1_Node000001_Node000002" title=" " alt="" coords="123,133,123,166,117,166,117,133"/>
<area shape="rect" id="Node000003" title=" " alt="" coords="77,5,163,31"/>
<area shape="poly" id="edge2_Node000002_Node000003" title=" " alt="" coords="123,44,123,79,117,79,117,44"/>
</map>
